// keywords.js
let DEFAULT_KEYWORDS = [
    "geotextile",
    "Geotextile",
    "geo-textile",
    "geo textile",
    "geofabric",
    "geo fabric",
    "TE-8",
    "TE-6",
    "TE-12",
    "geosynthetic",
    "geotex",
    "non woven",
    "non-woven",
    "nonwoven",
    "Monofilament",
    "textile",
    "synthetic fibre fabric",
    "filter fabric",
    "ASTM D-4632",
    "ASTM D4632",
    "Earth Grid",
    "geogrid",
    "geo grid",
    "bi axial",
    "bi-axial",
    "biaxial",
    "fiberglass grid",
    "glasgrid",
    "swamp grid",
    "combigrid",
    "combi grid",
    "combi-grid",
    "Miragrid",    
    "titan enviro",
    "titan environmental",
    "mirafi",
    "tencate",
    "layfield",
    "solmax",
    "Propex",
    "tensar",
    "NAUE",
    "armtec",
    "terrafix",
    "nilex",
    "Coletanche",
    "agru america",
    "BGM",
    "GCL",
    "BentoGard",
    "bentonite",
    "bentoliner",
    "geosynthetic clay liner",
    "geomembrane",
    "geo membrane",
    "membrane",
    "EPDM liner",
    "PVC liner",
    "LLDPE liner",
    "HDPE liner",
    "RPE liner",
    "40mil LLDPE",
    "40mil HDPE",
    "60mil HDPE",
    "HAZGARD",
    "XR-5",
    "XR-3",
    "GEOFLEX",
    "secondary containment",
    "concrete protective liner",
    "Studliner",
    "Sure-Grip",
    "Sure Grip",
    "concrete liner",
    "CONCRETE LINING SYSTEM",
    "Liner sheet",
    "ultra grip",
    "HDPE pipe liner",
    "ClosureTurf",
    "geonet",
    "geocomposite",
    "Biplanar",
    "triplanar",
    "hydranet",
    "composite grid",
    "composite geo",
    "geocell",
    "geo cell",
    "Geoweb",
    "Tough Cell",
    "stormwater system",
    "storm water system",
    "Stormwater Storage",
    "StormTank",
    "soil cell",
    "baffle curtain",
    "concrete canvas",
    "Geosynthetic Cementitious Composite Mat",
    "hi-40",
    "foamular 400",
    "rigid insulation",
    "erosion control",
    "erosion control blanket",
    "ErosionControlBlanket",
    "ECB",
    "TE-SC32",
    "TE-C32",
    "stenlog",
    "wattle",
    "sediment log",
    "ditch check",
    "bio-log",
    "silt fence", 
    "TE100SF",
    "silt curtain",
    "sediment control",
    "turbidity curtain",
    "W315",
    "safety boom",
    "cable concrete",
    "shoreflex",
    "flexamat",
    "Concrete Matting",
    "articulated concrete",
    "articulating concrete",
    "cable concrete",
    "TRM",
    "turf reinforcement",
    "turf-reinforcement",
    "pyramat",
    "landlok",
    "Armormax",
    "Fabrinet",
    "drain tile",
    "subdrain",
    "weeping tile",
    "drainage tile",
    "perforated HDPE",
    "HDPE drain pipe",
    "frenchdrain",
    "french drain",
    "high density polyethylene",
    "diameter HDPE",
    "dual wall",
    "culvert",
    "corrugated steel",
    "CSP",
    "nyloplast",
    "gabions",
    "MSE Wall",
    "stabilized earth",
    "reinforced soil",
    "multiflow",
    "multi-flow",
    "multi flow",
    "coffer dam",
    "cofferdam",
    "Aquadam",
    "Dewatering Bag",
    "Silt Bag",
    "Geotube",
    "desludging",   
    "detectable warning tile",
    "warning tile",
    "detectable tile",
    "detectable warning systems",
    "ADA tile",
    "armor-tile",
    "armortile",
    "armor tile",
    "radon",
    "radon barrier"
];

// Load from browser memory if user has made edits, otherwise use the list above
let saved = localStorage.getItem('tender_keywords');
window.KEYWORDS = saved ? JSON.parse(saved) : DEFAULT_KEYWORDS;

function saveKeywords() {
    localStorage.setItem('tender_keywords', JSON.stringify(window.KEYWORDS));
}

// Helper to reset to defaults if needed
function resetKeywords() {
    if(confirm("Reset to original list from keywords.js?")) {
        localStorage.removeItem('tender_keywords');
        location.reload();
    }
}
